<?php

/**
 * This file is part of the mimmi20/ua-data-mapper package.
 *
 * Copyright (c) 2015-2026, Thomas Mueller <mimmi20@live.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types = 1);

namespace UaDataMapper;

use function mb_strtolower;

/**
 * class with caching and update capabilities
 */
final class BrowserNameMapper
{
    /**
     * mapps the browser
     *
     * @throws void
     *
     * @api
     */
    public function mapBrowserName(string | null $browserInput): string | null
    {
        if ($browserInput === null) {
            return null;
        }

        return match (mb_strtolower($browserInput)) {
            'unknown', 'other', 'default browser', 'generic', 'misc crawler', 'generic bot', 'http library', 'ios', 'playstation 3', 'playstation 4' => null,
            'ie', 'msie' => 'Internet Explorer',
            'iceweasel' => 'Iceweasel',
            'mobile safari', 'mobile safari/wkwebview', 'safari mobile', 'webview', 'mobile safari uiwebview' => 'Safari',
            'chrome mobile ios', 'chrome frame', 'chrome for ios', 'crios', 'chrome mobile', 'mobile chrome' => 'Chrome',
            'android', 'android browser', 'aliyun browser' => 'Android Webkit',
            'googlebot', 'google bot mobile', 'adsbot google-mobile', 'adsbot google', 'google web preview', 'google publisher wordpress plugin', 'google web snippet', 'google ads conversions', 'google ads qualify', 'google adwords displayads webrender', 'google-inspectiontool' => 'Google Bot',
            'bingbot', 'bing preview', 'bingpreview', 'adidxbot' => 'BingBot',
            'jakarta commons-httpclient' => 'Jakarta Commons HttpClient',
            'adsbot-google' => 'AdsBot Google',
            'seokicks-robot', 'seokicks robot', 'seokicks' => 'SEOkicks Robot',
            'gomeza', 'gomezagent' => 'Gomez Site Monitor',
            'yandex.browser', 'yandex search browser' => 'Yandex Browser',
            'ie mobile' => 'IEMobile',
            'ovi browser', 'nokia/s40ovi', 'nokia ovi browser' => 'Nokia Proxy Browser',
            'firefox mobile', 'mobile firefox mobile', 'mobile firefox tablet', 'mobile firefox', 'firefox mobile for ios', 'firefox mobile ios', 'firefox for ios', 'firefox ios', 'fxios' => 'Firefox',
            'dolfin/jasmine webkit', 'dolphin' => 'Dolfin',
            'facebookexternalhit', 'facebook external hit', 'facebookbot' => 'FaceBook Bot',
            'facebook', 'facebook app' => 'Facebook App',
            'facebook messenger', 'facebook messenger app' => 'Facebook Messenger App',
            'instagram', 'instagram app' => 'Instagram App',
            'java' => 'Java Standard Library',
            'nokia web browser' => 'Nokia Browser',
            'applemail' => 'Apple Mail',
            'sistrix', 'sistrix crawler' => 'Sistrix Crawler',
            'blackberry webkit', 'blackberry browser', 'blackberry playbook browser' => 'BlackBerry',
            'microsoft outlook' => 'Outlook',
            'outlook express', 'microsoft outlook express' => 'Windows Live Mail',
            'mj12 bot' => 'MJ12bot',
            'mobile silk', 'amazon silk' => 'Silk',
            'genieo web filter' => 'Genieo Web Filter',
            'yahoo! slurp', 'slurp', 'inktomi slurp' => 'Slurp',
            'yandex bot', 'yandex mobile bot' => 'YandexBot',
            'nutch-based bot', 'apache nutch', 'testcrawler' => 'Nutch',
            'baidu spider', 'baiduspider', 'baidu mobile search', 'baidu transcoder' => 'BaiduSpider',
            'semrush bot' => 'SemrushBot',
            'python urllib' => 'Python-urllib',
            'mail.ru bot', 'mail.ru' => 'Mail.Ru Bot',
            'exabot' => 'Exabot',
            'curl' => 'cURL',
            'pale moon (firefox variant)', 'pale moon' => 'PaleMoon',
            'opera next', 'opera mobile' => 'Opera',
            'opera mini for ios', 'opera mini ios' => 'Opera Mini for iOS',
            'yeti/naverbot', 'adsbot naver' => 'NaverBot',
            'ahrefs bot' => 'AhrefsBot',
            'picsearch bot' => 'Picsearch Bot',
            'androiddownloadmanager' => 'Android Download Manager',
            'elinks' => 'ELinks',
            'whitehat aviator' => 'Aviator',
            'fake browser', 'fake ie', 'fake chrome', 'fake safari', 'fake firefox', 'fake android' => 'Fake Browser',
            'wdg html validator' => 'HTML Validator',
            'blekkobot' => 'BlekkoBot',
            'tweetmemebot', 'tweetmeme bot' => 'Tweetmeme Bot',
            'coremedia', 'applecoremedia' => 'CoreMedia',
            'mediapartners-google', 'google mediapartners' => 'AdSense Bot',
            'wordpress.com' => 'WordPress',
            'up.browser', 'au by kddi' => 'Openwave Mobile Browser',
            'qqbrowser' => 'QQ Browser',
            'wosbrowser', 'webkit/webos' => 'webOS Browser',
            'microsoft edge', 'spartan', 'edge mobile for ios', 'edge mobile', 'edge mobile for android' => 'Edge',
            'seomoz rogerbot' => 'roger bot',
            'airwatch browser', 'vmware airwatch' => 'AirWatch Browser',
            'google search app', 'google mobile app' => 'Google Search App',
            'microsoft office' => 'Microsoft Office',
            'office mobile', 'microsoft office mobile' => 'Microsoft Office Mobile',
            'word', 'microsoft office word' => 'Microsoft Word',
            'onenote', 'microsoft office onenote' => 'Microsoft OneNote',
            'powerpoint', 'microsoft office powerpoint' => 'Microsoft PowerPoint',
            'excel', 'microsoft office excel' => 'Microsoft Excel',
            'microsoft bing', 'bing search', 'bingweb app' => 'Microsoft Bing',
            'via browser', 'via' => 'Via Browser',
            'f-secure safe', 'safe' => 'SAFE',
            'chrome webview', 'android webview' => 'Chrome WebView',
            'start', 'microsoft start' => 'Start',
            'kodi', 'kodi media center' => 'Kodi',
            'keplr', 'keplr wallet' => 'Keplr',
            'canopy - ai online safety app', 'canopy' => 'Canopy',
            'genspark', 'genspark ai workspace' => 'Genspark',
            'wechat', 'wechat app' => 'WeChat',
            'omshy vpn', 'omshy vpn - secure vpn proxy' => 'Omshy VPN',
            'dezor', 'dezor browser' => 'Dezor',
            'youtube', 'youtube app' => 'YouTube',
            'news home', 'news home: news home screen' => 'News Home',
            'podcasts', 'apple podcasts' => 'Podcasts',
            'twitter', 'x' => 'X',
            'crosswalk app', 'crosswalkapp' => 'Crosswalk App',
            'jelly browser', 'jelly' => 'Jelly Browser',
            'moyaapp', 'moya' => 'MoyaApp',
            'cast to tv+', 'castify' => 'Cast to TV+',
            'cici', 'cici - your ai assistant' => 'Cici',
            'veilig virusscanner', 'kpn veilig' => 'Veilig Virusscanner',
            'nytimes - crossword', 'the crossword' => 'NYTimes - Crossword',
            'npr', 'npr: national & local news' => 'NPR',
            'quora app', 'quora' => 'Quora App',
            'nintendo browser', 'nintendobrowser' => 'Nintendo Browser',
            'dorado wap browser', 'dorado' => 'Dorado WAP Browser',
            'podverse', 'podverse - podcast player' => 'Podverse',
            'jack & jones to go', 'jj2go' => 'Jack & Jones to go',
            'internet security', 'swisscom internet security' => 'Internet Security',
            'mobile security', 'f-secure mobile security' => 'Mobile Security',
            'xing app', 'xing' => 'XING App',
            'super cleaner', 'phone clean' => 'Super Cleaner',
            'bonprix', 'bonprix app' => 'BonPrix',
            'blazer', 'palm blazer' => 'Blazer',
            'xbmc media center', 'xbmc' => 'XBMC Media Center',
            'wget' => 'wget',
            'epiphany', 'gnome web' => 'Epiphany',
            'amigavoyager', 'amiga voyager' => 'AmigaVoyager',
            'yacy bot', 'yacy' => 'YaCy Bot',
            'mosaic', 'ncsa mosaic' => 'Mosaic',
            'fresco', 'ant fresco' => 'Fresco',
            'web pro', 'palm webpro' => 'Web Pro',
            'telegram app', 'telegram' => 'Telegram App',
            'oceanhero browser', 'oceanhero' => 'OceanHero Browser',
            'stargon browser', 'stargon' => 'Stargon Browser',
            'puffin', 'puffin web browser' => 'Puffin',
            'slack app', 'slack' => 'Slack App',
            'radio.de app', 'radio.de' => 'radio.de App',
            'guzzle http client', 'guzzle (php http client)' => 'Guzzle Http Client',
            'sogou web spider', 'sogou spider' => 'Sogou Web Spider',
            'headline bot', 'headline' => 'headline bot',
            'hubspot crawler', 'hubspot' => 'HubSpot Crawler',
            'kindle browser', 'kindle' => 'Kindle Browser',
            'comodo dragon', 'dragon' => 'Comodo Dragon',
            'evernote app', 'evernote' => 'Evernote App',
            'foss browser' => 'Foss Browser',
            'lens', 'google lens' => 'Lens',
            'sodes', '\'sodes' => 'Sodes',
            'browser app' => 'Browser App',
            'imessage', 'apple imessage' => 'iMessage',
            'reminders', 'apple reminders' => 'Reminders',
            'cliqz browser', 'cliqz' => 'Cliqz Browser',
            'onebrowser', 'one browser' => 'OneBrowser',
            'docomo browser', 'docomo' => 'DoCoMo Browser',
            'amazon bot', 'amazonbot' => 'Amazon Bot',
            'maui wap browser', 'maui browser' => 'MAUI Wap Browser',
            'apple tv app', 'apple tv' => 'Apple TV App',
            'netflix app', 'netflix' => 'Netflix App',
            'avant', 'avant browser' => 'Avant',
            'k-meleon' => 'K-Meleon',
            'easouspider', 'easou spider' => 'EasouSpider',
            'atomic browser', 'atomic web browser' => 'Atomic Browser',
            'beonex communicator', 'beonex' => 'Beonex Communicator',
            'surfbrowser', 'surf' => 'SurfBrowser',
            't-online browser', 't-online.de browser' => 'T-Online Browser',
            'iridium browser', 'iridium' => 'Iridium Browser',
            'coc coc browser', 'coc coc' => 'Coc Coc Browser',
            'adbeat bot', 'adbeat' => 'Adbeat Bot',
            'quark', 'quarkpc' => 'Quark',
            'norton secure browser', 'norton private browser' => 'Norton Secure Browser',
            'daum app', 'daum' => 'Daum App',
            'pingdom', 'pingdom bot' => 'Pingdom Bot',
            'pinterest', 'pinterest bot','pinterest app' => 'Pinterest',
            'rddocuments app', 'rddocuments' => 'RDDocuments App',
            'google+ app', 'google plus' => 'Google+ App',
            'weibo app', 'sina weibo' => 'Weibo App',
            'zite app', 'zite' => 'Zite App',
            'vlc media player', 'vlc' => 'VLC Media Player',
            'qtweb internet browser', 'qtweb' => 'QtWeb Internet Browser',
            'facebook groups app', 'facebook groups' => 'Facebook Groups App',
            'firefox focus', 'firefox klar' => 'Firefox Focus',
            'whale browser', 'whale tv browser' => 'Whale Browser',
            'lightspeed systems crawler', 'lightspeedsystemscrawler' => 'Lightspeed Systems Crawler',
            'woorank', 'woorank review' => 'WooRank',
            'tbrowser', 't-browser' => 'TBrowser',
            'player fm', 'alpha player fm' => 'Player FM',
            'grapeshotcrawler', 'grapeshot' => 'GrapeshotCrawler',
            'rssradio podcast player', 'rssradio', 'rssradio bot' => 'RSSRadio Podcast Player',
            '1password', '1passwordthumbs' => '1Password',
            'obigo', 'obigo q' => 'Obigo',
            'ccleaner', 'ccleaner browser' => 'CCleaner',
            'amazon video bot', 'amazonbot-video' => 'Amazon Video Bot',
            'builtwith', 'builtwith crawler' => 'BuiltWith',
            'huawei browser', 'huawei browser mobile' => 'Huawei Browser',
            'petalbot', 'petal bot' => 'PetalBot',
            'goo', 'ichiro mobile bot' => 'Goo',
            'magpie crawler', 'magpie-crawler' => 'Magpie Crawler',
            'linkdex bot', 'linkdex mobile bot' => 'Linkdex Bot',
            'newsblur', 'newsblur feed fetcher', 'newsblur favicon fetcher' => 'NewsBlur',
            'orange bot', 'voilabot' => 'Orange Bot',
            'spinn3r', 'spinn3r rss aggregator' => 'Spinn3r',
            'surveybot', 'survey bot' => 'SurveyBot',
            'gazeta bot', 'yandex.gazeta bot' => 'Gazeta Bot',
            'chrome plus', 'chromeplus' => 'Chrome Plus',
            'netcraft survey agent', 'netcraft survey bot' => 'Netcraft Survey Agent',
            'optimizer bot', 'sistrix optimizer' => 'Optimizer Bot',
            'go httpclient', 'go-http-client' => 'GO HttpClient',
            'duckduck bot', 'duckduckbot' => 'DuckDuck Bot',
            'ccbot', 'ccbot crawler' => 'CCBot',
            'nagios check http', 'nagios check_http' => 'Nagios Check Http',
            'seobilitybot', 'seobility' => 'SeobilityBot',
            'chatgpt user bot', 'chatgpt-user' => 'ChatGPT User Bot',
            'seekportbot', 'seekport' => 'SeekportBot',
            'startmebot', 'start.me' => 'startmebot',
            'internet archive', 'archive.org bot' => 'Internet Archive',
            't3versionsbot', 't3versions' => 't3versionsBot',
            'sqalix', 'sqalix multiworker', 'sqalix geralworker' => 'sqalix',
            'gpt bot', 'gptbot' => 'GPT Bot',
            'bitsightbot', 'bitsight' => 'BitSightBot',
            'seznambot', 'seznam bot' => 'SeznamBot',
            'iframely bot', 'iframely' => 'Iframely Bot',
            'owler bot', 'owler' => 'Owler Bot',
            'google notebooklm', 'google-notebooklm' => 'Google NotebookLM',
            'mistralai user', 'mistralai-user' => 'MistralAI User',
            'perplexitybot', 'perplexity user', 'perplexity-user' => 'PerplexityBot',
            'meta externalagent', 'meta-externalagent' => 'Meta ExternalAgent',
            'website info bot', 'website-info' => 'Website Info Bot',
            '2ip bot', '2ip' => '2ip bot',
            'symfony rss reader', 'sffeedreader' => 'Symfony RSS Reader',
            'dataprovider spider', 'dataprovider' => 'Dataprovider Spider',
            'comscore crawler', 'comscore' => 'Comscore Crawler',
            'gemini deep research', 'gemini-deep-research' => 'Gemini Deep Research',
            'flowsurf', 'flow browser' => 'Flowsurf',
            'linkedinbot', 'linkedin bot' => 'LinkedInBot',
            'meta external ads', 'meta-externalads' => 'Meta External Ads',
            'arquivo web crawler', 'arquivo.pt' => 'Arquivo Web Crawler',
            'juzibrowser', 'juzi browser' => 'JuziBrowser',
            'yandex image search', 'yandeximages' => 'Yandex Image Search',
            'alltheweb', 'fast webcrawler' => 'AlltheWeb',
            'odin browser', 'odin' => 'Odin Browser',
            default => $browserInput,
        };
    }
}
