<?php

/**
 * This file is part of the mimmi20/ua-data-mapper package.
 *
 * Copyright (c) 2015-2026, Thomas Mueller <mimmi20@live.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types = 1);

namespace UaDataMapper;

use function mb_strtolower;

/**
 * class with caching and update capabilities
 */
final class DeviceBrandnameMapper
{
    /**
     * maps the brand name of a device
     *
     * @throws void
     *
     * @api
     */
    public function mapDeviceBrandName(string | null $brandName): string | null
    {
        if ($brandName === null) {
            return null;
        }

        return match (mb_strtolower($brandName)) {
            '', 'unknown', 'other', 'various' => null,
            'htc corporation', 'ht', 'htc' => 'HTC',
            'au', 'asus' => 'Asus',
            'sa', 'samsung' => 'Samsung',
            'so', 'sony' => 'Sony',
            'rm', 'blackberry', 'rim', 'black-berry' => 'BlackBerry',
            'nk', 'nokia' => 'Nokia',
            'ac', 'acer' => 'Acer',
            'go', 'google' => 'Google',
            'le', 'md', 'lenovo' => 'Lenovo',
            'mr', 'motorola' => 'Motorola',
            'kn', 'amazon' => 'Amazon',
            'hu', 'huawei' => 'Huawei',
            'ni', 'nintendo' => 'Nintendo',
            'ap', 'apple inc', 'apple' => 'Apple',
            'al', 'alcatel' => 'Alcatel',
            'mb', 'mobistel' => 'Mobistel',
            'wi', 'wiko' => 'Wiko',
            'xi', 'xiaomi' => 'Xiaomi',
            'ar', 'archos' => 'Archos',
            'kz', 'kazam' => 'KAZAM',
            'ms', 'microsoft' => 'Microsoft',
            'mi', 'micromax' => 'Micromax',
            'philips' => 'Philips',
            'ulefone' => 'Ulefone',
            'vivo' => 'Vivo',
            'oppo' => 'OPPO',
            'oneplus' => 'OnePlus',
            'realme' => 'Realme',
            'infinix' => 'Infinix',
            'zte' => 'ZTE',
            'oukitel' => 'Oukitel',
            'tecno', 'tecno mobile' => 'Tecno',
            'vasoun' => 'VASOUN',
            'teclast' => 'Teclast',
            'bmax' => 'BMAX',
            'nothing', 'nothing-phone' => 'Nothing',
            'hmd-global', 'hmd' => 'HMD Global',
            'oscal' => 'OSCAL',
            'doogee' => 'Doogee',
            'nubia' => 'Nubia',
            'blackview' => 'Blackview',
            'cubot' => 'CUBOT',
            'f150', 'iiif150' => 'iiiF150',
            'poco' => 'POCO',
            'meizu' => 'Meizu',
            'cmf' => 'CMF',
            'tcl', 'tcl scbc' => 'TCL',
            'pritom' => 'Pritom',
            'itel' => 'iTel',
            'casper' => 'Casper',
            'unihertz' => 'Unihertz',
            'zuum' => 'Zuum',
            'digma' => 'Digma',
            'onn' => 'ONN',
            'agm' => 'AGM',
            'fujitsu' => 'Fujitsu',
            'kalley' => 'Kalley',
            'lt mobile', 'lt-mobile' => 'LT Mobile',
            'meta' => 'Meta',
            'acd' => 'ACD',
            'alldocube' => 'AllDocube',
            'gtx' => 'GTX',
            'kenshi' => 'KENSHI',
            'lunnen' => 'LUNNEN',
            'ajib' => 'Ajib',
            'corn' => 'CORN',
            'reeder' => 'Reeder',
            'fossibot', 'fossi-bot' => 'FOSSiBOT',
            'sharp' => 'Sharp',
            'symphony' => 'Symphony',
            'cricket' => 'Cricket',
            'logic' => 'Logic',
            't-mobile', 'telekom' => 'T-Mobile',
            'atmpc' => 'ATMPC',
            'globalsec', 'global-sec' => 'GlobalSec',
            'stylo' => 'Stylo',
            'blu' => 'Blu',
            'hammer' => 'Hammer',
            'jambo' => 'Jambo',
            'krüger&matz', 'kruger-matz' => 'Krüger&Matz',
            'vitumi' => 'Vitumi',
            'homatics' => 'Homatics',
            'pixus' => 'Pixus',
            'n-one' => 'N-one',
            'tibuta' => 'Tibuta',
            'xb' => 'XB',
            'ziovo' => 'ZIOVO',
            'qiuwoky' => 'Qiuwoky',
            'colorroom' => 'COLORROOM',
            'hometech' => 'Hometech',
            'premier', 'premier star' => 'Premier',
            'umidigi', 'umi' => 'UMIDIGI',
            'logicom' => 'Logicom',
            'walton' => 'Walton',
            'at&t', 'at-t' => 'AT&T',
            'm-horse' => 'M-Horse',
            'general mobile', 'general-mobile' => 'General Mobile',
            'hotwav' => 'Hotwav',
            'kgtel' => 'KGTEL',
            'volla' => 'Volla',
            'mortal' => 'MORTAL',
            'homii' => 'HOMII',
            'villaon' => 'VILLAON',
            'maxwest' => 'Maxwest',
            'trecfone' => 'Trecfone',
            'aligator' => 'Aligator',
            'vgo tel', 'vgo-tel' => 'VGO TEL',
            'atozee' => 'Atozee',
            'wopad' => 'Wopad',
            'dcode' => 'Dcode',
            'novey' => 'Novey',
            'sparx' => 'Sparx',
            'vocal' => 'VOCAL',
            'sky' => 'Sky',
            'toscido' => 'TOSCIDO',
            'oysters' => 'Oysters',
            'chuwi' => 'Chuwi',
            'biegedy' => 'Biegedy',
            'dish', 'boost-mobile', 'boost mobile' => 'DISH',
            'ace' => 'Ace',
            'cepter' => 'CEPTER',
            'headwolf', 'head-wolf' => 'HeadWolf',
            'padpro' => 'Padpro',
            'energizer' => 'Energizer',
            'nuu mobile', 'nuu-mobile', 'nuu' => 'NUU Mobile',
            'lava' => 'Lava',
            'xreal' => 'XREAL',
            'ihunt' => 'iHunt',
            'kyocera' => 'Kyocera',
            'vortex' => 'Vortex',
            'm-kopa' => 'M-KOPA',
            'lg' => 'LG',
            'dexp' => 'DEXP',
            'wildred' => 'WildRed',
            'asano' => 'Asano',
            'hi' => 'Hi',
            'scoole' => 'Scoole',
            'soundmax' => 'Soundmax',
            'topdevice', 'top-device' => 'TopDevice',
            'bigben' => 'Bigben',
            'onvo' => 'ONVO',
            'krono' => 'KRONO',
            'calme' => 'CALME',
            'yumkem' => 'YUMKEM',
            'rungee' => 'RunGee',
            'vios' => 'Vios',
            'fanvace' => 'Fanvace',
            'gigaset' => 'Gigaset',
            'rombica' => 'Rombica',
            'novis' => 'NOVIS',
            'v7' => 'V7',
            'apolosign', 'apolo-sign' => 'ApoloSign',
            'multilaser' => 'Multilaser',
            'condor' => 'Condor',
            'fairphone' => 'Fairphone',
            'hot pepper', 'hot-pepper' => 'Hot Pepper',
            'omix' => 'OMIX',
            'mobvoi' => 'Mobvoi',
            'senna' => 'SENNA',
            'nesons' => 'Nesons',
            'openbox' => 'Openbox',
            'whoop' => 'Whoop',
            'iget' => 'iGet',
            'hanson' => 'Hanson',
            'xgody' => 'Xgody',
            'olax' => 'Olax',
            'allcall' => 'AllCall',
            'cloud', 'cloud-mobile', 'cloud mobile' => 'Cloud',
            'benco' => 'Benco',
            'safaricom' => 'Safaricom',
            'anbernic' => 'ANBERNIC',
            'retroid pocket', 'retroid-pocket' => 'Retroid Pocket',
            'x-view' => 'X-View',
            'fontel' => 'FONTEL',
            'consung' => 'CONSUNG',
            'peaq' => 'PEAQ',
            'sowly' => 'SOWLY',
            'hafury' => 'Hafury',
            'mione' => 'Mione',
            'pagraer' => 'PAGRAER',
            'coolpad' => 'Coolpad',
            'unophone', 'uno-phone' => 'UnoPhone',
            'grünberg', 'gruenberg' => 'Grünberg',
            'erisson' => 'Erisson',
            'akai' => 'Akai',
            'saba' => 'Saba',
            'onyx boox', 'onyx-boox' => 'ONYX BOOX',
            'ghia' => 'Ghia',
            'fenoti' => 'Fenoti',
            'meswao' => 'MESWAO',
            'vale' => 'VALE',
            'eudora' => 'Eudora',
            'cuiud' => 'Cuiud',
            'vertu' => 'Vertu',
            'ugoos' => 'Ugoos',
            'vorcom' => 'Vorcom',
            'mediacom' => 'Mediacom',
            'adreamer' => 'Adreamer',
            'hemilton' => 'Hemilton',
            'catsound' => 'catsound',
            'saiet' => 'Saiet',
            'syco' => 'Syco',
            'mobiwire', 'mobi-wire' => 'MobiWire',
            'nordmende' => 'Nordmende',
            'sber' => 'Sber',
            'newal' => 'Newal',
            'vision technology', 'vision-technology', 'vision' => 'Vision Technology',
            'haier' => 'Haier',
            'oangcc' => 'Oangcc',
            'inoi' => 'Inoi',
            'magch' => 'MAGCH',
            'nec' => 'NEC',
            'zzb' => 'ZZB',
            'egotek' => 'EGOTEK',
            'weelikeit' => 'Weelikeit',
            'hezire' => 'Hezire',
            'feonal' => 'FEONAL',
            'green lion', 'green-lion' => 'Green Lion',
            'honkuahg' => 'HONKUAHG',
            'aocwei' => 'Aocwei',
            'thomson' => 'Thomson',
            'relndoo' => 'Relndoo',
            'majestic' => 'Majestic',
            'aauw' => 'AAUW',
            'facetel' => 'Facetel',
            'flycoay' => 'FLYCOAY',
            'jumper' => 'Jumper',
            'clovertek' => 'Clovertek',
            'visual land', 'visual-land' => 'Visual Land',
            'blow' => 'Blow',
            'lville' => 'Lville',
            'eaglesoar', 'eagle-soar' => 'EagleSoar',
            'hoozo' => 'Hoozo',
            'wainyok' => 'Wainyok',
            'maxcom' => 'Maxcom',
            'ayya' => 'AYYA',
            'xsmart', 'x-smart' => 'Xsmart',
            'mobicel' => 'Mobicel',
            'hisense' => 'Hisense',
            'meanit' => 'meanIT',
            'allview' => 'Allview',
            'f+', 'f-plus' => 'F+',
            'moondrop' => 'Moondrop',
            'rhino' => 'Rhino',
            'sonim' => 'Sonim',
            'zebra' => 'Zebra',
            'freeyond', 'free-yond' => 'FreeYond',
            'memobile', 'me-mobile' => 'MeMobile',
            'x-mobile' => 'X-Mobile',
            'emporia' => 'Emporia',
            'dijitsu' => 'DIJITSU',
            'daria' => 'Daria',
            'bmobile' => 'Bmobile',
            'soho style', 'soho-style' => 'Soho Style',
            'veidoo' => 'Veidoo',
            'opelmobile', 'opel-mobile', 'opel mobile' => 'OpelMobile',
            'dudu-auto', 'dudu auto' => 'dudu-auto',
            'crosscall' => 'crosscall',
            'maze-speed', 'maze speed' => 'maze-speed',
            'foxxd' => 'FoxxD',
            's-color' => 'S-Color',
            'higrace', 'hi-grace' => 'HiGrace',
            'myphone', 'myphone (pl)' => 'MyPhone',
            'idata' => 'iData',
            'mintt' => 'Mintt',
            'sigma mobile', 'sigma-mobile', 'sigma' => 'Sigma Mobile',
            'goodtel' => 'GOODTEL',
            'iotwe' => 'IOTWE',
            'vontar' => 'Vontar',
            'ibrit' => 'iBrit',
            'readboy' => 'Readboy',
            'eplutus' => 'Eplutus',
            'techpad' => 'TechPad',
            'blaupunkt' => 'Blaupunkt',
            'great asia', 'great-asia' => 'Great Asia',
            'fmt' => 'FMT',
            'lanix' => 'Lanix',
            'x-tigi' => 'X-TIGI',
            'yestel' => 'Yestel',
            'blackton' => 'Blackton',
            'sebbe' => 'SEBBE',
            'doro' => 'Doro',
            'iconbit' => 'IconBIT',
            'kinstone' => 'Kinstone',
            'ruggear' => 'RugGear',
            'sunmax' => 'Sunmax',
            'medion' => 'Medion',
            'kempler & strauss', 'kempler-strauss' => 'Kempler & Strauss',
            'wortmann', 'terra' => 'Wortmann',
            'redline' => 'RedLine',
            'magenta' => 'Magenta',
            'china telecom', 'china-telecom' => 'China Telecom',
            'skyworth', 'sky-worth' => 'Skyworth',
            'land rover', 'land-rover' => 'Land Rover',
            'insys' => 'INSYS',
            'spc' => 'SPC',
            'conquest' => 'Conquest',
            'klipad' => 'Klipad',
            'polaroid' => 'Polaroid',
            'telia' => 'Telia',
            'bell' => 'Bell',
            'everfine' => 'Everfine',
            'jusyea' => 'JUSYEA',
            'acepad' => 'Acepad',
            'korax' => 'Korax',
            'xppen', 'xp-pen' => 'XPPen',
            'dmoao' => 'DMOAO',
            'atouch' => 'Atouch',
            'canaima' => 'Canaima',
            'smooth mobile', 'smooth-mobile' => 'Smooth Mobile',
            'qlink' => 'QLink',
            'ox tab', 'ox-tab' => 'OX TAB',
            'transpeed' => 'Transpeed',
            'sk broadband', 'sk-broadband' => 'SK Broadband',
            'gotv', 'go-tv' => 'GOtv',
            'honor' => 'Honor',
            'mecool' => 'Mecool',
            'imo', 'imo mobile' => 'IMO',
            'jio' => 'Jio',
            'yezz' => 'Yezz',
            'dgtec' => 'DGTEC',
            'enova' => 'eNOVA',
            'wozifan' => 'WOZIFAN',
            'tjd' => 'TJD',
            'rocket' => 'Rocket',
            'qilive' => 'Qilive',
            'sunwind', 'sun-wind' => 'SunWind',
            'neoregent' => 'Neoregent',
            'hi nova', 'hi-nova' => 'Hi Nova',
            'bq' => 'BQ',
            'andersson' => 'Andersson',
            'positivo' => 'Positivo',
            'brondi' => 'Brondi',
            'orbic' => 'Orbic',
            'pcd', 'pcd argentina' => 'PCD',
            'chcnav' => 'CHCnav',
            'ans' => 'ANS',
            'dynalink', 'dinalink' => 'Dynalink',
            'aiwa' => 'Aiwa',
            'jide', 'jedi' => 'Jide',
            'sonyericsson', 'sony ericsson' => 'SonyEricsson',
            'multynet' => 'Multynet',
            'arcelik', 'arçelik' => 'Arcelik',
            'texet' => 'TeXet',
            'cat', 'caterpillar' => 'Cat',
            'tesla', 'tesla motors' => 'Tesla',
            'qihoo 360', '360' => 'Qihoo 360',
            default => $brandName,
        };
    }
}
